### ISSUE TITLE
Week 6+7: Standard CNN + Making Convolutional Networks Shift-Invariant Again

### ISSUE THREAD

**Issue by wsgdrfz** [wsgdrfz/Antialiased-SSCNN#5]
This week task:

- Read and discuss the paper: [Making Convolutional Networks Shift-Invariant Again](https://arxiv.org/pdf/1904.11486)
- Read and understand the code
- Run the code and test using same dataset
- Write the network for standard CNN with almost same architecture
- Write the survey part of this paper
!! Better the read the mentioned paper in background to prepare for the final report "Background" part. At least mark the paper.

**Comment by wsgdrfz** [comment]
Week 7 work assignment:
1. First paper details:  Check in paper and code, which method been used: scale the image or scale the filter? Is three filters same and always same?
2. Second paper: after for every iteration, does`weight_all` change?
3. Adding shift-invariance to second paper.

Wei: 1&2
Ruoqi: 3

**Comment by AprilV** [comment]
2. `weight_all` did updates through `optimizer.step()`
But after updates the linear combination may not stay consistent.
